# Generated by MedLang compiler
# Model: OneCompOral
# Backend: Julia (DifferentialEquations.jl + Turing.jl)

using DifferentialEquations
using Turing
using Distributions
using DataFrames
using LinearAlgebra

# ODE system for OneCompOral
function ode_system!(du, u, p, t)
    A_gut = u[1]
    A_central = u[2]

    Ka = p[1]
    CL = p[2]
    V = p[3]

    # Differential equations
    du[1] = (-Ka * A_gut)
    du[2] = ((Ka * A_gut) - ((CL / V) * A_central))
end

# Turing.jl probabilistic model
@model function OneCompOral(data, n_subjects)
    # Extract data
    times = data.TIME
    observations = data.DV
    subject_ids = data.ID
    WT = data.WT

    # Population parameter priors
    CL_pop ~ LogNormal(log(10.0), 1.0)
    V_pop ~ LogNormal(log(50.0), 1.0)
    Ka_pop ~ LogNormal(log(1.0), 1.0)
    omega_CL ~ truncated(Cauchy(0, 1), 0, Inf)
    omega_V ~ truncated(Cauchy(0, 1), 0, Inf)
    omega_Ka ~ truncated(Cauchy(0, 1), 0, Inf)

    # Inter-individual variability
    eta_CL = Vector{Float64}(undef, n_subjects)
    for i in 1:n_subjects
        eta_CL[i] ~ Normal(0, omega_CL)
    end
    eta_V = Vector{Float64}(undef, n_subjects)
    for i in 1:n_subjects
        eta_V[i] ~ Normal(0, omega_V)
    end
    eta_Ka = Vector{Float64}(undef, n_subjects)
    for i in 1:n_subjects
        eta_Ka[i] ~ Normal(0, omega_Ka)
    end

    # Individual parameters
    CL = Vector{Float64}(undef, n_subjects)
    for i in 1:n_subjects
        w = WT[i] / 70.0  # Normalized weight
        CL[i] = ((CL_pop * (w ^ 0.75)) * exp(eta_CL[i]))
    end
    V = Vector{Float64}(undef, n_subjects)
    for i in 1:n_subjects
        w = WT[i] / 70.0  # Normalized weight
        V[i] = ((V_pop * w) * exp(eta_V[i]))
    end
    Ka = Vector{Float64}(undef, n_subjects)
    for i in 1:n_subjects
        w = WT[i] / 70.0  # Normalized weight
        Ka[i] = (Ka_pop * exp(eta_Ka[i]))
    end

    # Measurement error model
    sigma_prop ~ truncated(Cauchy(0, 1), 0, Inf)

    # Likelihood
    for obs_idx in 1:length(observations)
        subj_id = subject_ids[obs_idx]
        t = times[obs_idx]

        # Solve ODE for this observation
        u0 = zeros(2)  # Initial conditions
        if t > 0.0
            u0[1] = 100.0  # Dose to first compartment (gut)
        end

        p = [Ka[subj_id], CL[subj_id], V[subj_id]]
        tspan = (0.0, t)
        prob = ODEProblem(ode_system!, u0, tspan, p)
        sol = solve(prob, Tsit5(), saveat=[t], abstol=1e-8, reltol=1e-8)

        # Compute predicted concentration
        pred = sol[2, end] / V[subj_id]  # A_central / V

        # Likelihood contribution
        observations[obs_idx] ~ Normal(pred, sigma_prop * pred)
    end
end

